version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper  
     
  pixel-service:
    build:
      context: ./PixelService/src
      dockerfile: Dockerfile
    ports:
      - "5101:8080"
    environment:
      KAFKA__BOOTSTRAPSERVER: kafka:9092
    depends_on:
      - kafka

  storage-service:
    build:
      context: ./StorageService/src
      dockerfile: Dockerfile
    ports:
      - "5102:8080"
    environment:
      KAFKA__BOOTSTRAPSERVER: kafka:9092
    depends_on:
      - kafka     